[2025-01-22T03:08:38.104+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T03:08:38.117+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-01-22T03:08:33.015958+00:00 [queued]>
[2025-01-22T03:08:38.123+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-01-22T03:08:33.015958+00:00 [queued]>
[2025-01-22T03:08:38.123+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-22T03:08:38.133+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_data> on 2025-01-22 03:08:33.015958+00:00
[2025-01-22T03:08:38.137+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T03:08:38.138+0000] {standard_task_runner.py:72} INFO - Started process 83 to run task
[2025-01-22T03:08:38.139+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nasa_dag', 'extract_data', 'manual__2025-01-22T03:08:33.015958+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/nasa_dag.py', '--cfg-path', '/tmp/tmp383x1l7r']
[2025-01-22T03:08:38.140+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask extract_data
[2025-01-22T03:08:38.175+0000] {task_command.py:467} INFO - Running <TaskInstance: nasa_dag.extract_data manual__2025-01-22T03:08:33.015958+00:00 [running]> on host 254510a8aaaa
[2025-01-22T03:08:38.235+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='milo0@gmail.com' AIRFLOW_CTX_DAG_OWNER='camilo' AIRFLOW_CTX_DAG_ID='nasa_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T03:08:33.015958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T03:08:33.015958+00:00'
[2025-01-22T03:08:38.236+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T03:08:38.247+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-22T03:08:38.248+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tmp/extract_api_nasa.py']
[2025-01-22T03:08:38.254+0000] {subprocess.py:86} INFO - Output:
[2025-01-22T03:08:40.682+0000] {subprocess.py:93} INFO - {'date': '2025-01-21', 'explanation': "What's that in the sky? Above the city, above most clouds, far in the distance: it's a comet. Pictured, the impressive tail of Comet C/2024 G3 (ATLAS) was imaged from Brasília, Brazil four days ago. Last week the evolving  comet rounded the Sun well inside the orbit of planet Mercury, going so close there was early concern that it might break up -- and recent evidence that it really did.  At one point near perihelion, Comet ATLAS was so bright that sightings were even reported during the day -- over the bright sky near the Sun -- by careful observers.  Over the past few days, Comet ATLAS has developed a long tail that has been partly visible with unaided eyes after sunset, most notably in Earth's southern hemisphere.    Growing Gallery: Comet ATLAS (G3)", 'hdurl': 'https://apod.nasa.gov/apod/image/2501/CometATLAS_Danin_1080.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Comet ATLAS over Brasília', 'url': 'https://apod.nasa.gov/apod/image/2501/CometATLAS_Danin_1080.jpg'}
[2025-01-22T03:08:40.683+0000] {subprocess.py:93} INFO - Nuevo objeto agregado al archivo /opt/***/tmp/data.json
[2025-01-22T03:08:40.716+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-22T03:08:40.734+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T03:08:40.735+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nasa_dag, task_id=extract_data, run_id=manual__2025-01-22T03:08:33.015958+00:00, execution_date=20250122T030833, start_date=20250122T030838, end_date=20250122T030840
[2025-01-22T03:08:40.769+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T03:08:40.782+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T03:08:40.783+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
