[2025-02-04T00:42:27.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T00:42:27.053+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-02-04T00:42:24.038614+00:00 [queued]>
[2025-02-04T00:42:27.062+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-02-04T00:42:24.038614+00:00 [queued]>
[2025-02-04T00:42:27.063+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-04T00:42:27.076+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_data> on 2025-02-04 00:42:24.038614+00:00
[2025-02-04T00:42:27.081+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=93) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T00:42:27.083+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-02-04T00:42:27.083+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nasa_dag', 'extract_data', 'manual__2025-02-04T00:42:24.038614+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/nasa_dag.py', '--cfg-path', '/tmp/tmpjbw_1z1o']
[2025-02-04T00:42:27.085+0000] {standard_task_runner.py:105} INFO - Job 245: Subtask extract_data
[2025-02-04T00:42:27.134+0000] {task_command.py:467} INFO - Running <TaskInstance: nasa_dag.extract_data manual__2025-02-04T00:42:24.038614+00:00 [running]> on host fbf16bed15ba
[2025-02-04T00:42:27.209+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='milo0@gmail.com' AIRFLOW_CTX_DAG_OWNER='camilo' AIRFLOW_CTX_DAG_ID='nasa_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:42:24.038614+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:42:24.038614+00:00'
[2025-02-04T00:42:27.210+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T00:42:27.224+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-04T00:42:27.226+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tmp/extract_api_nasa.py']
[2025-02-04T00:42:27.235+0000] {subprocess.py:86} INFO - Output:
[2025-02-04T00:42:31.501+0000] {subprocess.py:93} INFO - {'date': '2025-02-03', 'explanation': 'Some stars explode in slow motion.  Rare, massive Wolf-Rayet stars are so tumultuous and hot that they are slowly disintegrating right before our telescopes.  Glowing gas globs each typically over 30 times more massive than the Earth are being expelled by violent stellar winds.  Wolf-Rayet star WR 124, visible near the featured image center, is thus creating the surrounding nebula known as M1-67, which spans six light years across. Details of why this star has been slowly blowing itself apart over the past 20,000 years remains a topic of research.  WR 124 lies 15,000 light-years away towards the constellation of the Arrow (Sagitta).  The fate of any given Wolf-Rayet star likely depends on how massive it is, but many are thought to end their lives with spectacular explosions such as supernovas or gamma-ray bursts.   Explore Your Universe: Random APOD Generator', 'hdurl': 'https://apod.nasa.gov/apod/image/2502/wr124_hubbleschmidt_1289.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Wolf-Rayet Star 124: Stellar Wind Machine', 'url': 'https://apod.nasa.gov/apod/image/2502/wr124_hubbleschmidt_960.jpg'}
[2025-02-04T00:42:31.502+0000] {subprocess.py:93} INFO - Nuevo objeto agregado al archivo /opt/***/tmp/data.json
[2025-02-04T00:42:31.550+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-04T00:42:31.574+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T00:42:31.575+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nasa_dag, task_id=extract_data, run_id=manual__2025-02-04T00:42:24.038614+00:00, execution_date=20250204T004224, start_date=20250204T004227, end_date=20250204T004231
[2025-02-04T00:42:31.613+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T00:42:31.635+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T00:42:31.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
