[2025-02-05T02:56:39.693+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T02:56:39.707+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_dag.create_data manual__2025-02-05T02:56:38.155447+00:00 [queued]>
[2025-02-05T02:56:39.714+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_dag.create_data manual__2025-02-05T02:56:38.155447+00:00 [queued]>
[2025-02-05T02:56:39.715+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-05T02:56:39.726+0000] {taskinstance.py:2888} INFO - Executing <Task(MongoDBOperator): create_data> on 2025-02-05 02:56:38.155447+00:00
[2025-02-05T02:56:39.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T02:56:39.733+0000] {standard_task_runner.py:72} INFO - Started process 72 to run task
[2025-02-05T02:56:39.732+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nasa_dag', 'create_data', 'manual__2025-02-05T02:56:38.155447+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/nasa_dag.py', '--cfg-path', '/tmp/tmpefrkdmd8']
[2025-02-05T02:56:39.734+0000] {standard_task_runner.py:105} INFO - Job 304: Subtask create_data
[2025-02-05T02:56:39.770+0000] {task_command.py:467} INFO - Running <TaskInstance: nasa_dag.create_data manual__2025-02-05T02:56:38.155447+00:00 [running]> on host fbf16bed15ba
[2025-02-05T02:56:39.824+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_dag' AIRFLOW_CTX_TASK_ID='create_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T02:56:38.155447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T02:56:38.155447+00:00'
[2025-02-05T02:56:39.825+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T02:56:39.844+0000] {base.py:84} INFO - Retrieving connection 'mongo_default'
[2025-02-05T02:56:39.845+0000] {mongodb_file_operator.py:41} INFO - Connecting to MongoDB with URI: mongodb+srv://camilopv:***@etlprocess.txf16.mongodb.net/etlprocess?retryWrites=true&w=majority
[2025-02-05T02:56:41.815+0000] {mongodb_file_operator.py:52} INFO - Collection nasa already exists
[2025-02-05T02:56:41.824+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T02:56:41.825+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nasa_dag, task_id=create_data, run_id=manual__2025-02-05T02:56:38.155447+00:00, execution_date=20250205T025638, start_date=20250205T025639, end_date=20250205T025641
[2025-02-05T02:56:41.878+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T02:56:41.899+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T02:56:41.903+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
